# Generated by Django 4.2.18 on 2025-02-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_alter_article_options_remove_article_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
