# Generated by Django 4.2.18 on 2025-02-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0005_rename_post_comment_article_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='Test', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
